### ISSUE TITLE
Is the order random?

### ISSUE THREAD

**Issue by codydunne** [VisDunneRight/UserStudyScatter#2]
I got these 4 in order: 
* 0_Geometric_distribution_0.05_32
* 0_DAWA_correlation_0.01_32
* 0_Geometric_correlation_0.5_32
* 0_Laplace_distribution_0.05_32.

Later on I got these 3 in order: 
* 2_DAWA_clusters_0.01_64
* 2_Geometric_clusters_0.1_64
* 2_DAWA_correlation_0.05_64 

That's fine if it was random, not ideal if there is some sorted order that groups them.

**Comment by Turokhunter** [comment]
Random order is generated when you first visit the site, and then the information is saved in local storage.

**Comment by Turokhunter** [comment]
Refreshing changes the questions.

**Comment by Turokhunter** [comment]
Fixed issue with the order not being saved in local storage.
